Add AKS OpenAI Embeddings workshop
microsoft/moaw pull request #71
Opened 2023-08-31 01:35 UTC by mosabami

We ran a levelup on this workshop earlier today that was attended by over 800 people with positive feedback. Looking to add this to the catalog so others can benefit from it

2023-08-31 07:01 UTC, sinedied requested changes
Thanks! I added 2 small comments to fix before merging

2023-08-31 07:01 UTC, sinedied commented on workshops/aks-openai-embeddings/workshop.md
> +published: false                        # Optional. Set to true to publish the workshop (default: false)
you should set this to `true` so it's searchable in the workshop list

2023-08-31 07:01 UTC, sinedied commented on workshops/aks-openai-embeddings/assets/banner.jpg
If you don't use a banner you can remove this file, it was meant as a placeholder to create you own

2023-08-31 18:12 UTC, mosabami commented
thanks @sinedied . Updated accordingly

2023-09-01 07:17 UTC, sinedied approved these changes

2023-09-01 07:17 UTC, merged

2024-01-17 16:45 UTC, sinedied commented
:tada: This PR is included in version 1.3.1 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@moaw/cli/v/1.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: